config/routes.rb
Petitionsite::Application.routes.draw do
  resources :signatures

  resources :petitions

  devise_for :users
  root :to => "staticpages#welcome"

end

app/models/petition.rb
class Petition < ActiveRecord::Base
end

app/models/signature.rb
class Signature < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  

end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  # GET /petitions
  # GET /petitions.json
  def index
    @petitions = Petition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @petitions }
    end
  end

  # GET /petitions/1
  # GET /petitions/1.json
  def show
    @petition = Petition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/new
  # GET /petitions/new.json
  def new
    @petition = Petition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/1/edit
  def edit
    @petition = Petition.find(params[:id])
  end

  # POST /petitions
  # POST /petitions.json
  def create
    @petition = Petition.new(params[:petition])

    respond_to do |format|
      if @petition.save
        format.html { redirect_to @petition, notice: 'Petition was successfully created.' }
        format.json { render json: @petition, status: :created, location: @petition }
      else
        format.html { render action: "new" }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /petitions/1
  # PUT /petitions/1.json
  def update
    @petition = Petition.find(params[:id])

    respond_to do |format|
      if params[:petition][:title] == @petition.title
        if @petition.update_attributes(params[:petition])
          format.html { redirect_to @petition, notice: 'Petition was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @petition.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "edit", notice: 'No changing of the petition title please!!!' }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
        
    end
  end

  # DELETE /petitions/1
  # DELETE /petitions/1.json
  def destroy
    before_filter :authenticate_user!
    @petition = Petition.find(params[:id])
    @petition.destroy

    respond_to do |format|
      format.html { redirect_to petitions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  # GET /signatures
  # GET /signatures.json
  def index
    @signatures = Signature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signatures }
    end
  end

  # GET /signatures/1
  # GET /signatures/1.json
  def show
    @signature = Signature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/new
  # GET /signatures/new.json
  def new
    @signature = Signature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/1/edit
  def edit
    @signature = Signature.find(params[:id])
  end

  # POST /signatures
  # POST /signatures.json
  def create
    logger.info "~"*30
    logger.info current_user.inspect
    logger.info "~"*30
    logger.info params[:petition_id]
    logger.info "~"*30
    @signature = Signature.new(params[:signature])
    @signature.user_id = current_user
    @signature.petition_id = params[:petition_id]
    respond_to do |format|
      if @signature.save
        format.html { redirect_to @signature, notice: 'Signature was successfully created.' }
        format.json { render json: @signature, status: :created, location: @signature }
      else
        format.html { render action: "new" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signatures/1
  # PUT /signatures/1.json
  def update
    @signature = Signature.find(params[:id])

    respond_to do |format|
      if @signature.update_attributes(params[:signature])
        format.html { redirect_to @signature, notice: 'Signature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signatures/1
  # DELETE /signatures/1.json
  def destroy
    @signature = Signature.find(params[:id])
    @signature.destroy

    respond_to do |format|
      format.html { redirect_to signatures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def welcome
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petitionsite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <p><%= render partial: "staticpages/header" %></p>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/petitions/_form.html.erb
<%= form_for(@petition) do |f| %>
  <% if @petition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petition.errors.count, "error") %> prohibited this petition from being saved:</h2>

      <ul>
      <% @petition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/petitions/edit.html.erb
<h1>Editing petition</h1>

<div class = "warning">Remember, you can't change the title of your petition.  Change the description all you want, that's totally your prerogative.  Just leave the title alone!</div>
<%= render 'form' %>

<%= link_to 'Show', @petition %> |
<%= link_to 'Back', petitions_path %>

app/views/petitions/index.html.erb
<h1>Listing petitions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @petitions.each do |petition| %>
  <tr>
    <td><%= petition.title %></td>
    <td><%= petition.description %></td>
    <td><%= link_to 'Show', petition %></td>
    <td><%= link_to 'Edit', edit_petition_path(petition) %></td>
    <td><%= link_to 'Sign This Petition!', signatures_path(:petition_id => petition.id), method: :post %></td>
    <td><%= link_to 'Destroy', petition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Petition', new_petition_path %>

app/views/petitions/new.html.erb
<h1>New petition</h1>

<%= render 'form' %>

<%= link_to 'Back', petitions_path %>

app/views/petitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @petition.title %>
</p>

<p>
  <b>Description:</b>
  <%= @petition.description %>
</p>


<%= link_to 'Edit', edit_petition_path(@petition) %> |
<%= link_to 'Back', petitions_path %>

app/views/signatures/_form.html.erb
<%= form_for(@signature) do |f| %>
  <% if @signature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signature.errors.count, "error") %> prohibited this signature from being saved:</h2>

      <ul>
      <% @signature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signatures/edit.html.erb
<h1>Editing signature</h1>

<%= render 'form' %>

<%= link_to 'Show', @signature %> |
<%= link_to 'Back', signatures_path %>

app/views/signatures/index.html.erb
<h1>Listing signatures</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signatures.each do |signature| %>
  <tr>
    <td><%= link_to 'Show', signature %></td>
    <td><%= link_to 'Edit', edit_signature_path(signature) %></td>
    <td><%= link_to 'Destroy', signature, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signature', new_signature_path %>

app/views/signatures/new.html.erb
<h1>New signature</h1>

<%= render 'form' %>

<%= link_to 'Back', signatures_path %>

app/views/signatures/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_signature_path(@signature) %> |
<%= link_to 'Back', signatures_path %>

app/views/staticpages/_header.html.erb
<ul><div class="heading">
<% if user_signed_in? %>
  <li><div class="button"><%= link_to "Sign Out", destroy_user_session_path %></div></li>
  <li><div class="button new-petition"><%= link_to "Create a Petition", new_petition_path %></div></li>
<% else %>
  <li><div class="button"><%= link_to "Sign In", new_user_session_path %></div></li> 
  <li><div class="button"><%= link_to "Sign Up", new_user_registration_path %></div></li>
<% end %>
  <li><div class="button"><%= link_to "View Current Petitions!", petitions_path %></div></li></ul>
</div>

app/views/staticpages/welcome.html.erb
<% if user_signed_in? %>

<div class='encouragement'><%= "Why, thank ya kindly for registering on our site and signing in.  Just click on that New Petition button up there and you're in business!" %> </div>

<% else %>

<div class="welcome">Thanks for coming to this totally awesome petition site, which of course has nothing to do with that pretender site change.org! </div>

<div class="explanation"><%= "Around here, folks like to be signed in before they just start a-makin petitions like they're goin' out of style.  So why don't you saddle up, get an account, sign in, and start changin' the world?" %> </div>

<% end %>